package com.coolooksdk.model;

import java.util.Date;

public class AppLockscreen {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.id
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.title
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.img
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.type
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.datatime
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Date datatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.isshow
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Short isshow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.src
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private String src;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.rank
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Short rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.versionid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Integer versionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.createuid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Integer createuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.createtime
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.countryid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Integer countryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.countrycode
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private String countrycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.langid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Integer langid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.channelid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Integer channelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.topicsid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Integer topicsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.attr
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Integer attr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.isscroll
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Integer isscroll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.sourceid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Integer sourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.imgsize
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Integer imgsize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.isfree
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private Integer isfree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lockscreen.abstracts
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    private String abstracts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.id
     *
     * @return the value of app_lockscreen.id
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.id
     *
     * @param id the value for app_lockscreen.id
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.title
     *
     * @return the value of app_lockscreen.title
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.title
     *
     * @param title the value for app_lockscreen.title
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.img
     *
     * @return the value of app_lockscreen.img
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.img
     *
     * @param img the value for app_lockscreen.img
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.type
     *
     * @return the value of app_lockscreen.type
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.type
     *
     * @param type the value for app_lockscreen.type
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.datatime
     *
     * @return the value of app_lockscreen.datatime
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Date getDatatime() {
        return datatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.datatime
     *
     * @param datatime the value for app_lockscreen.datatime
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setDatatime(Date datatime) {
        this.datatime = datatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.isshow
     *
     * @return the value of app_lockscreen.isshow
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Short getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.isshow
     *
     * @param isshow the value for app_lockscreen.isshow
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setIsshow(Short isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.src
     *
     * @return the value of app_lockscreen.src
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.src
     *
     * @param src the value for app_lockscreen.src
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.rank
     *
     * @return the value of app_lockscreen.rank
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Short getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.rank
     *
     * @param rank the value for app_lockscreen.rank
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setRank(Short rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.versionid
     *
     * @return the value of app_lockscreen.versionid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Integer getVersionid() {
        return versionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.versionid
     *
     * @param versionid the value for app_lockscreen.versionid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setVersionid(Integer versionid) {
        this.versionid = versionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.createuid
     *
     * @return the value of app_lockscreen.createuid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Integer getCreateuid() {
        return createuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.createuid
     *
     * @param createuid the value for app_lockscreen.createuid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setCreateuid(Integer createuid) {
        this.createuid = createuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.createtime
     *
     * @return the value of app_lockscreen.createtime
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.createtime
     *
     * @param createtime the value for app_lockscreen.createtime
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.countryid
     *
     * @return the value of app_lockscreen.countryid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Integer getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.countryid
     *
     * @param countryid the value for app_lockscreen.countryid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setCountryid(Integer countryid) {
        this.countryid = countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.countrycode
     *
     * @return the value of app_lockscreen.countrycode
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.countrycode
     *
     * @param countrycode the value for app_lockscreen.countrycode
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode == null ? null : countrycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.langid
     *
     * @return the value of app_lockscreen.langid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Integer getLangid() {
        return langid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.langid
     *
     * @param langid the value for app_lockscreen.langid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setLangid(Integer langid) {
        this.langid = langid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.channelid
     *
     * @return the value of app_lockscreen.channelid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Integer getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.channelid
     *
     * @param channelid the value for app_lockscreen.channelid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setChannelid(Integer channelid) {
        this.channelid = channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.topicsid
     *
     * @return the value of app_lockscreen.topicsid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Integer getTopicsid() {
        return topicsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.topicsid
     *
     * @param topicsid the value for app_lockscreen.topicsid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setTopicsid(Integer topicsid) {
        this.topicsid = topicsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.attr
     *
     * @return the value of app_lockscreen.attr
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Integer getAttr() {
        return attr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.attr
     *
     * @param attr the value for app_lockscreen.attr
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setAttr(Integer attr) {
        this.attr = attr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.isscroll
     *
     * @return the value of app_lockscreen.isscroll
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Integer getIsscroll() {
        return isscroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.isscroll
     *
     * @param isscroll the value for app_lockscreen.isscroll
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setIsscroll(Integer isscroll) {
        this.isscroll = isscroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.sourceid
     *
     * @return the value of app_lockscreen.sourceid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Integer getSourceid() {
        return sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.sourceid
     *
     * @param sourceid the value for app_lockscreen.sourceid
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setSourceid(Integer sourceid) {
        this.sourceid = sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.imgsize
     *
     * @return the value of app_lockscreen.imgsize
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Integer getImgsize() {
        return imgsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.imgsize
     *
     * @param imgsize the value for app_lockscreen.imgsize
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setImgsize(Integer imgsize) {
        this.imgsize = imgsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.isfree
     *
     * @return the value of app_lockscreen.isfree
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public Integer getIsfree() {
        return isfree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.isfree
     *
     * @param isfree the value for app_lockscreen.isfree
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setIsfree(Integer isfree) {
        this.isfree = isfree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lockscreen.abstracts
     *
     * @return the value of app_lockscreen.abstracts
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public String getAbstracts() {
        return abstracts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lockscreen.abstracts
     *
     * @param abstracts the value for app_lockscreen.abstracts
     *
     * @mbg.generated Tue May 08 15:56:10 CST 2018
     */
    public void setAbstracts(String abstracts) {
        this.abstracts = abstracts == null ? null : abstracts.trim();
    }
}